spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://ep-dawn-term-aqr3ah9d-pooler.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l3Y5ohniajRK

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
